# Generated by Django 2.0.6 on 2020-10-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_day2', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(default='pic/1.jpg', upload_to='pic/'),
        ),
    ]
