# Generated by Django 2.0.6 on 2020-10-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_day2', '0004_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='bz_teacher',
        ),
    ]
